config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users
  # get "/account_activations/:id/edit", to: "account_activations#edit"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products
  get "products_count", to: "products#count"

  resources :orders
  get "orders/:id/state/:next_state", to: "orders#change"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders # 商品可以被许多用户购买

  default_scope -> { order(created_at: :desc) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :accept_all_params

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :body,
      :mileage,
      :engV,
      :engType,
      :registration,
      :year,
      :model,
      :drive
    )
  end

  def count
    res = Product.unscoped.group(:name).count
    render :json => res
  end

  def index
    name = params[:search]
    if (name)
      # case-insensitive search for name
      @products = Product
        .where("lower(name) LIKE lower(?) OR lower(name) LIKE lower(?)", "%#{name}%", "%#{name}%")
        .paginate(page: params[:page], per_page: 10)
      # .where("lower(name) = ?", name.downcase)
      # where("name LIKE '%#{params[:search]}%'")
    else
      @products = Product.where(del: 0).paginate(page: params[:page], per_page: 10)
    end
  end

  # get create new
  def new
    @product = Product.new
  end

  # post create
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:info] = "ok"
    else
      flash[:error] = "create error"
    end
    redirect_to products_url
  end

  # get one product
  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  # patch /
  def update
    @product = Product.find(params[:id])
    if @product.update!(product_params)
      flash[:success] = "product updated"
      redirect_to @product
    else
      render "edit"
    end
  end

  def destroy
    # 不是真的删除, 只是修改状态不显示
    flash[:success] = "admin success deleted"
    product = Product.find(params[:id])
    product.del = 1
    product.save!
    redirect_to products_url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<% provide(:title, "Edit product") %>
<h1 class="text-center">edit the product</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
        <%= render "shared/error_messages", collection: @product, as: :item %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_field :body, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :mileage %>
            <%= f.text_field :mileage, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :engV %>
            <%= f.text_field :engV, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :engType %>
            <%= f.text_field :engType, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :registration %>
            <%= f.text_field :registration, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :year %>
            <%= f.text_field :year, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :model %>
            <%= f.text_field :model, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :drive %>
            <%= f.text_field :drive, class: "form-control" %>
        </div>
        
        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

 </div>
</div>

app/views/products/index.html.erb
<% provide(:title, "Index") %>

<div class="page-header">
  <% if isAdmin %>
      <%= link_to "add new product  ( admin only )", new_product_path, class: "pull-right btn btn-primary" %>
  <% end %>

  <% if current_user %>
    <h1>Hello, <%= current_user.name %> <small>welcome to Ireney used car store!</small></h1>
  <% else %>
    <h1>Hello, Guest <small>welcome to Ireney used car store! you can login or sign up</small></h1>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <div id="charts" style="width: 100%;height:600px;">
    </div>
    <script type="text/javascript">
        function jump() {
          var val = document.getElementById('search').value;
          location.href = val === '' ? '/' : '/?search=' + val;
        }
        $(function() {
          $('#search').keyup(function(event){  
            if(event.keyCode ==13){  
              jump();
            }  
          }); 
          var myChart = echarts.init(document.getElementById('charts'));
          myChart.showLoading();
          $.get('/products_count').done(function (data) {
              var sort_arr = [], x_hot = [], y_hot = [];
              for(var key in data){
                var val = data[key];
                sort_arr.push({ key: key, val: val});
              }
              var arr = sort_arr.sort(function f(a,b) { return b.val - a.val });
              arr.forEach(function(it) {
                x_hot.push(it.key);
                y_hot.push(it.val);
              });
    var option = {
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'shadow',
                label: {
                    show: true
                }
            }
        },
        toolbox: {
            show: true,
            feature: {
                mark: {show: true},
            }
        },
        calculable: true,
        legend: {
            data: ['amounts'],
            itemGap: 5
        },
        grid: {
            top: '12%',
            left: '1%',
            right: '10%',
            containLabel: true
        },
        xAxis: { data: x_hot },
        yAxis: {},
        dataZoom: [
            {
                show: true,
                start: 0,
                end: 100
            },
            {
                type: 'inside',
                start: 94,
                end: 100
            },
            {
                show: true,
                yAxisIndex: 0,
                filterMode: 'empty',
                width: 30,
                height: '80%',
                showDataShadow: false,
                left: '93%'
            }
        ],
        series: [
            {
                name: 'amout',
                type: 'bar',
                data: y_hot
            },
        ]
    };

              myChart.setOption(option);
              myChart.hideLoading();
          });
        });
    </script>
  </div>
  <div class="col-lg-12">
    <div class="input-group">
      <input id="search" type="text" class="form-control" placeholder="Search for brand, enter to search">
      <span class="input-group-btn">
        <button onclick="jump()" class="btn btn-default" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

</div><!-- /.row -->

<table class="table table-hover">
  <thead>
    <th>cars</th>
    <th>year</th>
    <th>mileage</th>
    <th>body</th>
    <th>engType</th>
    <th>price</th>
    <th></th>
    <% if isAdmin %>
    <th>control (  only admin can see )</th>
    <% end %>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to product.name + "  " + product.model, product %>
      </td>
      <td><%= product.year %></td>
      <td><%= product.mileage %></td>
      <td><%= product.body %></td>
      <td><%= product.engType %></td>
      <td style=""><%= product.price %></td>      
      <td><%= link_to "buy now", new_order_path(pid: product.id) %></td>      
      <% if isAdmin %>
        <td>
          <%= link_to "edit", edit_product_path(product) %>
          | <%= link_to("delete", product, method: :delete, data: { confirm: "Are you sure?" }) %>
        </td>      
      <% end %>

    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/products/new.html.erb
<% provide(:title, "Create new Product") %>
<h1 class="text-center">Create new Product</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
 
    <%= form_for(@product) do |f| %>
        <%= render "shared/error_messages", collection: @product, as: :item %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_field :body, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :mileage %>
            <%= f.text_field :mileage, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :engV %>
            <%= f.text_field :engV, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :engType %>
            <%= f.text_field :engType, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :registration %>
            <%= f.text_field :registration, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :year %>
            <%= f.text_field :year, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :model %>
            <%= f.text_field :model, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :drive %>
            <%= f.text_field :drive, class: "form-control" %>
        </div>

        <%= f.submit "create a car", class: "btn btn-primary" %>
    <% end %>

 </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>


<div class="page-header">
  <h1>
  Car Detail: <%= @product.name + "  " + @product.model %> 
  <br>
  the price only :  <i> <%= @product.price %> Now!!!</i>
  </h1>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
            <dt>body</dt>
            <dd><%= @product.body %></dd>
            <dt>mileage</dt>
            <dd><%= @product.mileage %></dd>
            <dt>engV</dt>
            <dd><%= @product.engV %></dd>
            <dt>engType</dt>
            <dd><%= @product.engType %></dd>
            <dt>registration</dt>
            <dd><%= @product.registration %></dd>
            <dt>year</dt>
            <dd><%= @product.year %></dd>
            <dt>model</dt>
            <dd><%= @product.model %></dd>
            <dt>drive</dt>
            <dd><%= @product.drive %></dd>
    </dl>
 </div>
  <div class="col-md-3">
      <%= link_to "buy it", new_order_path(pid: @product.id), class: "btn btn-primary btn-lg" %>
      <% if isAdmin %>
        <%= link_to "edit the info", edit_product_path(@product), class: "btn btn-info btn-lg" %>
        <% end %>
   </div>

</div>
  <h1>the map to search the position</h1>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">  
function createMarker(map, point, content) {
  var marker = new google.maps.Marker({
    position: point,
    map: map
  });
  google.maps.event.addListener(marker, "click", function(evt) {
    infowindow.setContent(content + "<br>" + marker.getPosition().toUrlValue(6));
    infowindow.open(map, marker);
  });
  return marker;
}

function initMap() {
  // The location of Uluru
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
</script>
<script src="//maps.google.com/maps/api/js?key=AIzaSyDMzvUhOVsGYyz9APhUueeF8Zi-qwTLRkA&callback=initMap"></script>  