config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users
  # get "/account_activations/:id/edit", to: "account_activations#edit"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products
  get "products_count", to: "products#count"

  resources :orders
  get "orders/:id/state/:next_state", to: "orders#change"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
 <div class="container">
    <%= link_to "Ireney used car store", root_path, class: "navbar-brand" %>
    <% # <p class="navbar-text">Signed in as Mark Otto</p> %>
    <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
           <% if isAdmin %>
                <li><%= link_to "All Payments", orders_path %></li>
                <li><%= link_to "All Users", users_path %></li>
            <% end %>
            <li><%= link_to "My Payment", current_user %></li>
            <li><%= link_to "Profile Edit", edit_user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
    </ul>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", media: "all",
                                           'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>

    <script crossorigin="anonymous" integrity="sha384-rY/jv8mMhqDabXSo+UCggqKtdmBfd3qC2/KvyTDNQ6PcUJXaxK1tMepoQda4g5vB" src="https://lib.baomitu.com/jquery/2.2.4/jquery.min.js"></script>
    <link crossorigin="anonymous" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" href="https://lib.baomitu.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" src="https://lib.baomitu.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-30FJF/gD+RPgQM+z59TEJ3Tn3IprMjn5HlEiTTRc8SOWGRNcfhWfto/7P/jCXy8o" src="https://lib.baomitu.com/echarts/4.7.0/echarts-en.common.min.js"></script>
 <!--[if lt IE 9]>
 <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
 </script>
 <![endif]-->
 </head>
 <body>


 <body>

    <%= render "layouts/header" %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
 
</body>
</html>